o_camera.target = o_player;
o_player.sprite_index = s_ghost_idle;
o_camera.cam_state = camera.cutscene;
global.state = noone;
spr_alpha = 1;
alpha = 0;
fade = false;
draw = false;
if !audio_is_playing(snd_wait_music) audio_play_sound(snd_wait_music,1,true);
audio_sound_gain(snd_wait_music,1,2000);
draw_set_font(f_description);
text[0] ="You arrive in purgatory, a small square-ish room with a few chairs along the walls, a small coffee table and or end table, ficus tree, the door you came in from, and a second door next to a small window. The room is clean, but not ostentatious at all.";
text_current = 0;
text_width = 640;
char_current = 1;
char_speed = .50;
text[text_current] = string_wrap(text[text_current], text_width);
_len = string_length(text[text_current]);
step = 0;
alarm[0] = 120;
if audio_is_playing(snd_wait_bell) audio_sound_gain(snd_wait_bell,0,2000);